# Site Settings
title: My Resume
url: 'https://treeforest456.github.io'
baseurl: '/online_cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Shuyu Wang
tagline: Machine Learning Engineer
pic: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Innovative problem solver experienced in data science. Critical thinker who can approach problems from
different angles. Organized and detail-oriented, with the ability to work in a fast-paced and deadline driven
environment. Effective communicator skilled in conveying ideas.'

#sidebar links
email: shuyuwang123@gmail.com
phone: 314 555 5555
website: treeforest456.github.io #do not add http://
linkedin: shuyuwangwiredin
github: treeforest456
twitter: ''
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
